# Generated by Django 4.2.8 on 2024-12-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('detected_objects', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analyze_result',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('class_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('box', models.JSONField()),
                ('analyze_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_detected_objects', to='analyze.analyzeresult')),
            ],
            options={
                'db_table': 'analyze_detectedobject',
                'managed': True,
            },
        ),
    ]
